In [1]:
import pandas as pd
import numpy as np
from numpy import median
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns', 999)

In [3]:
data_path = "C:/Users/armcl/Python/Springboard_Cap2/Data/" #Home
#data_path = "C:/Users/yyzhao/python/Springboard/Capstone1/Data/" #Work

In [9]:
#Read customers data
customers = pd.read_csv(data_path + "customers.csv", encoding="utf8")

customers = customers.drop(columns = ['note','ship_street','ship_unit','location',
                                     'wrr','last4','source','customer_metadata',
                                     'ship_phone_number'])

#some observations are missing location data, # of orders, and might have wrong name
#will investigate once merged with other data

In [10]:
#mrr: monthly recurring revenue
#mixed subscription status: once subscribed, cancelled, subscribed again
customers.head()

,customer_id,first_name,last_name,name,email,ship_to,ship_city,ship_state,ship_zip_code,ship_country,country,total_revenue,mrr,num_orders,num_subscriptions,subscription_status,payment_provider,marketplace_source
0,2739202452,Jennifer,Ting,Jennifer Ting,muchenting@hotmail.com,Jennifer Ting,San Ramon,CA,94583,US,US,27500,2375.0,1,1,active,STRIPE,False
1,2729781565,Caelyn,Furman,Caelyn Furman,caelyn.furman@gmail.com,Caelyn Furman,Avondale Esates,GA,30002,US,US,18590,0.0,2,0,none,STRIPE,False
2,2728145736,Amy,Zhang,Amy Zhang,julie.dev.yu@gmail.com,Amy Zhang,Seattle,WA,98107,US,US,7490,0.0,1,0,none,STRIPE,False
3,2715897926,Jingwen,Zhen,Jingwen Zhen,zjeanwen@hotmail.com,Jingwen Zhen,Chicago,IL,60616,US,US,1872,2495.0,1,1,active,STRIPE,False
4,2715863750,Lin,Cao,Lin Cao,mrslydia@hotmail.com,Lin Cao,Claymont,DE,19703,US,US,5580,0.0,1,0,none,STRIPE,False

In [12]:
customers.shape

(1320, 18)

In [13]:
customers.describe()

,customer_id,total_revenue,mrr,num_orders,num_subscriptions
count,1.320000e+03,1320.000000,1320.000000,1320.000000,1320.000000
mean,2.053670e+09,12926.550758,645.079545,3.173485,1.017424
std,3.030278e+08,17243.366640,1145.304993,3.426392,0.555215
min,7.880641e+07,0.000000,0.000000,0.000000,0.000000
25%,1.864414e+09,1796.000000,0.000000,1.000000,1.000000
50%,1.937069e+09,5287.500000,0.000000,2.000000,1.000000
75%,2.279912e+09,19777.000000,2090.000000,4.000000,1.000000
max,2.739202e+09,146892.000000,9500.000000,22.000000,5.000000

In [23]:
import codecs
f = codecs.open("C:/Users/armcl/Python/Springboard_Cap2/Data/subscriptions.csv", "r", "utf-8") 
f

In [22]:
subscriptions = pd.read_csv(data_path + "subscriptions.csv", encoding="GBK")
subscriptions.head()

UnicodeDecodeError: 'gbk' codec can't decode byte 0x95 in position 73: illegal multibyte sequence